#ifndef NUALINK_CONFIG_H
#define NUALINK_CONFIG_H

#define NUALINK_FIRMWARE_VERSION "0.1.0"
#define NUALINK_PROTOCOL_VERSION "2024-11-05"
#define NUALINK_BASELINE_TAG "v0.1.0-usb-cdc-stable"

/*
 * Runtime logging controls.
 * - NUALINK_ENABLE_DEBUG_LOG: high-frequency diagnostic logs (USB state, frame traces).
 * - NUALINK_ENABLE_BOOT_DIAGNOSTICS: verbose boot-stage logs.
 */
#define NUALINK_ENABLE_DEBUG_LOG 0
#define NUALINK_ENABLE_BOOT_DIAGNOSTICS 0

#define NUALINK_USB_RX_PACKET_SIZE 512U
#define NUALINK_JSON_REQUEST_SIZE 1024U
#define NUALINK_JSON_RESPONSE_SIZE 2048U

#define NUALINK_REQUEST_QUEUE_LENGTH 2U
#define NUALINK_RESPONSE_QUEUE_LENGTH 2U

#define NUALINK_USB_TX_TIMEOUT_MS 250U
#define NUALINK_HEARTBEAT_PERIOD_MS 500U

#endif /* NUALINK_CONFIG_H */